"""Build architecture comparison table from per-arch metrics.json files."""
from __future__ import annotations

import json

from config import ARCHITECTURE_COMPARISON_PATH, ARCHITECTURES, arch_metrics_path


def _load_metrics() -> dict[str, dict]:
    found = {}
    for arch in ARCHITECTURES:
        path = arch_metrics_path(arch)
        if path.exists():
            with open(path) as f:
                found[arch] = json.load(f)
        else:
            print(f"[skip] no metrics found for '{arch}' at {path} -- run "
                  f"`python train.py --arch {arch}` then `python evaluate.py --arch {arch}` first.")
    return found


def _fmt_pct(x: float) -> str:
    return f"{100 * x:.2f}%"


def build_table(metrics_by_arch: dict[str, dict]) -> str:
    lines = []
    lines.append("# Priority 1 -- Sensor Architecture Comparison\n")
    lines.append(
        "Generated by `compare_architectures.py` from `experiments/<arch>_metrics.json` "
        "(ActionPlan.md section 9.2/9.3). Re-run after evaluating any architecture to refresh.\n"
    )
    lines.append(
        "| Model | Macro Precision | Macro Recall | Macro F1 | Accuracy | "
        "Latency (ms/sample) | Params | Size (KB) | Worst 5 classes (by F1) |"
    )
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---|")

    for arch in ARCHITECTURES:
        m = metrics_by_arch.get(arch)
        if m is None:
            lines.append(f"| {arch} | - | - | - | - | - | - | - | not yet evaluated |")
            continue
        worst = ", ".join(f"{c['char']}({c['f1']:.2f})" for c in m.get("worst_5_classes_by_f1", []))
        lines.append(
            f"| {arch} | {_fmt_pct(m['macro_precision'])} | {_fmt_pct(m['macro_recall'])} | "
            f"{_fmt_pct(m['macro_f1'])} | {_fmt_pct(m['accuracy'])} | "
            f"{m['median_single_sample_latency_ms']:.2f} | {m['num_params']:,} | "
            f"{m['model_size_bytes'] / 1024:.1f} | {worst} |"
        )

    lines.append("")

    if metrics_by_arch:
        ranked = sorted(metrics_by_arch.items(), key=lambda kv: kv[1]["macro_f1"], reverse=True)
        best_arch, best_metrics = ranked[0]
        lines.append(
            f"**Highest Macro F1:** `{best_arch}` ({_fmt_pct(best_metrics['macro_f1'])}).\n"
        )
        if len(ranked) < len(ARCHITECTURES):
            missing = [a for a in ARCHITECTURES if a not in metrics_by_arch]
            lines.append(
                f"_Not all architectures evaluated yet (missing: {', '.join(missing)}) -- "
                f"this ranking may change once they are._\n"
            )
        lines.append(
            "Per ActionPlan.md 9.3, don't select purely on this number: also check the "
            "worst-class F1 column above (robustness), latency, and model size before "
            "picking the Global Sensor Model used for every downstream priority. "
            "\"Highest Macro F1\" is a starting point, not an automatic pick.\n"
        )
    else:
        lines.append("_No architectures evaluated yet._\n")

    return "\n".join(lines)


def main() -> None:
    metrics_by_arch = _load_metrics()
    table = build_table(metrics_by_arch)
    print(table)

    ARCHITECTURE_COMPARISON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(ARCHITECTURE_COMPARISON_PATH, "w") as f:
        f.write(table)
    print(f"\n[save] {ARCHITECTURE_COMPARISON_PATH}")


if __name__ == "__main__":
    main()
